2401
The-FinAI/PIXIU pull request #44
Opened 2024-01-04 11:11 UTC by Me1oyy

Update README.md

2024-01-04 11:54 UTC, jiminHuang requested changes

2024-01-04 11:54 UTC, jiminHuang commented on README.md
> +| Lending Club          | credit scoring                   | 1,3453 | financial information     | table             | CC0 1.0         | [16]  |
Have these tasks been added to the flare.py?

2024-01-06 11:54 UTC, Me1oyy commented
tasks have been added to flare.py and __init__.py

2024-01-07 15:14 UTC, jiminHuang requested changes

2024-01-07 15:14 UTC, jiminHuang commented on src/tasks/__init__.py
> +    "lengdingclub": flare.lendingclub,
Please follow our task naming rules, formatting as "flare_"

2024-01-08 08:39 UTC, Me1oyy commented
tasks names changed

2024-02-22 18:52 UTC, closed without merging